version: '3'

services:
  fastapi-helloworld:
    container_name: fastapi-helloworld
    build:
      context: .
      dockerfile: Dockerfile          
    ports:
      - "5000:5000"    
    environment:
      - HELLOWORLD_ENV=enrique catala